# Generated by Django 4.2.4 on 2023-11-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10)),
                ('classe_del_eleve', models.CharField(choices=[('7emeEB', '7e EB'), ('8emeEB', '8e EB'), ('1ere', '1ère des Humanités'), ('2eme', '2ème des Humanités'), ('3eme', '3ème des Humanités'), ('4eme', '4ème des Humanités'), ('-', '-')], default='-', max_length=30, verbose_name="classe de l'élève")),
                ('date_de_naissance', models.DateTimeField(null=True)),
                ('lieu_de_naissance', models.CharField(max_length=30)),
                ('tuteur', models.CharField(max_length=30)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.option')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('classe', models.CharField(choices=[('7emeEB', '7e EB'), ('8emeEB', '8e EB'), ('1ere', '1ère des Humanités'), ('2eme', '2ème des Humanités'), ('3eme', '3ème des Humanités'), ('4eme', '4ème des Humanités'), ('-', '-')], default='-', max_length=30, verbose_name='Classe')),
                ('heures', models.IntegerField(default=25)),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.prof')),
            ],
            options={
                'verbose_name': 'Cours',
            },
        ),
    ]
