# Generated by Django 4.2.4 on 2023-11-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof',
            options={'verbose_name': 'Professeur'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Elève'},
        ),
        migrations.AlterField(
            model_name='student',
            name='tuteur',
            field=models.CharField(max_length=30, verbose_name='Responsable'),
        ),
    ]
