# Generated by Django 4.2.4 on 2023-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_date_de_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fiche',
            field=models.FileField(null=True, upload_to='fiches_cotation/<django.db.models.fields.CharField>'),
        ),
    ]
