# Generated by Django 4.2.4 on 2023-11-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_grade_alter_course_fiche_alter_student_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Classe'},
        ),
        migrations.AlterField(
            model_name='course',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade', verbose_name='Classe'),
        ),
    ]
