# Generated by Django 4.2.4 on 2023-11-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_grade_options_alter_course_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classe_del_eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.option'),
        ),
    ]
