# Generated by Django 4.2.4 on 2023-11-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_student_classe_del_eleve_alter_student_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fiche',
            field=models.FileField(default='fches_cotation/default/default.xls', null=True, upload_to='fiches_cotation'),
        ),
    ]
