# Generated by Django 4.2.4 on 2023-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_course_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fiche',
            field=models.FileField(default='fiches_cotation/default/default.xls', null=True, upload_to='fiches_cotation'),
        ),
    ]
