# Generated by Django 5.0 on 2024-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_grade_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='liste_eleves',
            field=models.FileField(null=True, upload_to='eleves'),
        ),
    ]
